// src/redux/analyticsSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for analytics data
const initialState = {
  totalRevenue: 10000,
  totalAppointments: 120,
  newClientsThisWeek: 50,
  topPerformingBarber: "John Doe",
  totalPayments: 8000,
  performanceOverTime: [200, 400, 300, 500, 600, 700, 800],
};

// Create the slice
const analyticsSlice = createSlice({
  name: "analytics",
  initialState,
  reducers: {
    setAnalyticsData: (state, action) => {
      return { ...state, ...action.payload };
    },
    updatePerformanceData: (state, action) => {
      state.performanceOverTime = action.payload;
    },
    // Add more actions here if needed
  },
});

// Export the actions generated by createSlice
export const { setAnalyticsData, updatePerformanceData } =
  analyticsSlice.actions;

// Export the reducer to be used in the store
export default analyticsSlice.reducer;
